const knex = require('knex');
const app = require('../src/app');
const config = require('../src/config');
const jwt = require('jsonwebtoken')
const { makeTestPages } = require('./pages.fixtures');
const { expect } = require('chai');
const supertest = require('supertest');
const PageService = require('../services/service.pages');

describe('|Page Routes Test Object|', function() {
    // Prepare Necessary Constants and Variables //
    let db;
    let testPages = makeTestPages();

     // Instantiate Knex Object //
     before('make knex instance', () => {
        db = knex(
            {
                client: "pg",
                connection: config.TEST_DATABASE_URL,
            }
        );
        app.set('db', db);
    })

    // Disconnect and Clean //
    after('disconnect from db', () => db.destroy());
    before('clean table', ()=> db.raw('TRUNCATE pages RESTART IDENTITY CASCADE'));
    
    // Begin Assertions //

    // Base Case for each fixture
    describe(`|POST Component | Site: ${testPages.pages[0].name} | /comps/create/:name `, () => { // Log what site is being tested
        it(`should post the component to the database and return with a UAT`, () => { // Try to add the comp to the database
                
            return supertest(app)
            .post(`/api/pages/create/${testPages.pages[0].name}`)
            .send(testPages.pages[0])
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(201)
            .then(res => {
                expect(res.body.page).to.have.property('id');
                expect(res.body.page).to.have.property('name');
                expect(res.body.page).to.have.property('created_at');
                expect(res.body.page).to.have.property('page_data');
                expect(res.body.page).to.have.property('updated_at');  // !important - this is generated by the SQL DB - if this fails something is wrong with the DB
            });
        });
    });

    describe(`|GET Page | Site: ${testPages.pages[0].name} | /pages/get/:name `, () => { // Log what site is being tested
        it(`should get the page from the database`, () => { // Try to get the comp to the database
                
            return supertest(app)
            .get(`/api/pages/get/${testPages.pages[0].name}`)
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200)
            .then(res => {
                expect(res.body.page[0]).to.have.property('id');
                expect(res.body.page[0]).to.have.property('name');
                expect(res.body.page[0]).to.have.property('created_at');
                expect(res.body.page[0]).to.have.property('page_data');
                expect(res.body.page[0]).to.have.property('updated_at');  // !important - this is generated by the SQL DB - if this fails something is wrong with the DB
            });
        });
    });

    describe(`|GET Pages | /pages/get `, () => { // Log what site is being tested
        it(`should get all the pages from the database`, () => { // Try to get the comps from the database
                
            return supertest(app)
            .get(`/api/pages/get`)
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200)
            .then(res => {
                res.body.pages.forEach(page => {
                    expect(page).to.have.property('id');
                    expect(page).to.have.property('name');
                    expect(page).to.have.property('created_at');
                    expect(page).to.have.property('page_data');
                    expect(page).to.have.property('updated_at');  // !important - this is generated by the SQL DB - if this fails something is wrong with the DB
                });
            });
        });
    });

    describe(`|PATCH Page | Site: ${testPages.pages[0].name} | /pages/update/:name `, () => { // Log what site is being tested
        it(`should update the page and change the name ${testPages.pages[0].name} to ${testPages.updatedPages[0].name}`, () => { // Try to add the site to the database
            return supertest(app)
            .patch(`/api/pages/update/${testPages.pages[0].name}`)
            .set('Accept', 'application/json')
            .send(testPages.updatedPages[0])
            .expect('Content-Type', /json/)
            .expect(200)
            .then(res => {
                expect(res.body.page).to.have.property('id');
                expect(res.body.page).to.have.property('name');
                expect(res.body.page).to.have.property('created_at');
                expect(res.body.page).to.have.property('page_data');
                expect(res.body.page).to.have.property('updated_at');  // !important - this is generated by the SQL DB - if this fails something is wrong with the DB
            });
        });
    });

    describe(`|GET Page | Site: ${testPages.updatedPages[0].name} | /pages/delete/:name `, () => { // Log what site is being tested
        it(`should delete the previously updated page from the database`, () => { // Try to add the site to the database
                
            return supertest(app)
            .delete(`/api/pages/delete/${testPages.updatedPages[0].name}`)
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(204);
        });
    });
});