const knex = require('knex');
const app = require('../src/app');
const config = require('../src/config');
const jwt = require('jsonwebtoken')
const { makeTestInstall } = require('./install.fixtures');
const { expect } = require('chai');
const supertest = require('supertest');
const InstallService = require('../services/service.data');
const { deleteSingleNavLink } = require('../services/service.data');

describe('|Install Routes Test Object|', function() {
    // Prepare Necessary Constants and Variables //
    let db;
    let testInstall = makeTestInstall();

     // Instantiate Knex Object //
     before('make knex instance', () => {
        db = knex(
            {
                client: "pg",
                connection: config.TEST_DATABASE_URL,
            }
        );
        app.set('db', db);
    })

    // Disconnect and Clean //
    after('disconnect from db', () => db.destroy());
    before('clean table', ()=> db.raw('TRUNCATE install RESTART IDENTITY CASCADE'));
    
    // Begin Assertions //

    // Base Case for each fixture
    describe(`|POST Stage One Install: New Site | Site: ${testInstall.install[0].name} | /install/:site `, () => { // Log what site is being tested
        it(`should post the site id and name with installed status false`, () => { // Try to add the site to the database
                
            return supertest(app)
            .post(`/api/install/${testInstall.install[0].id}`)
            .send(testInstall.install[0])
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(201)
            .then(res => {
                expect(res.body.install).to.have.property('installed', false); // !important - this should be false at this stage
                expect(res.body.install).to.have.property('id');
                expect(res.body.install).to.have.property('name');
                expect(res.body.install).to.have.property('created_at');
                expect(res.body.install).to.have.property('updated_at');  // !important - this is generated by the SQL DB - if this fails something is wrong with the DB
            });
        });
    });
});